# app.yaml
# 必須項目です
runtime: php55
api_version: 1
threadsafe: true

handlers:
  - url: /
    script: prof.php
    secure: always
  - url: /(.+\.php)
    script: \1
    secure: always
  - url: /(.+\.(css|js|jpg|png))
    static_files: \1
    upload: (.+\.(css|js|jpg|png))
    secure: always
  - url: /(.+\.txt)
    script: \1
    secure: always
  - url: /.*
    script: 404.php
    secure: always
